data:
  train_labeled_data_path: "./data/Training/labeled_data"
  train_source_data_path: "./data/Training/source_data"

model:
  model_name: "klue/bert-base"
  train_param: 
    output_dir: "./outputs"
    logging_dir: "./logging_dir"
    logging_strategy: "epochs"
    lr: 0.00005
    batch_size: 16
    eval_batch_size: 16
    epoch: 3
    weight_decay: 0.01
    eval_strategy: 200
    save_steps: 200
    logging_steps: 50
    save_total_limit: 2
    push_to_hub: False
    report_to: "none"
    max_length: 128